/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as AnalyticsIndexRouteImport } from './routes/analytics.index'
import { Route as AnalyticsAlertsRouteImport } from './routes/analytics.alerts'
import { Route as AnalyticsClaimsRouteImport } from './routes/analytics.claims'
import { Route as AnalyticsClinicalRouteImport } from './routes/analytics.clinical'
import { Route as AnalyticsCohortsRouteImport } from './routes/analytics.cohorts'
import { Route as AnalyticsExecutiveRouteImport } from './routes/analytics.executive'
import { Route as AnalyticsLaboratoryRouteImport } from './routes/analytics.laboratory'
import { Route as AnalyticsNewChartsRouteImport } from './routes/analytics.new-charts'
import { Route as AnalyticsPatientExperienceRouteImport } from './routes/analytics.patient-experience'
import { Route as AnalyticsPatternsRouteImport } from './routes/analytics.patterns'
import { Route as AnalyticsPerformanceRouteImport } from './routes/analytics.performance'
import { Route as AnalyticsQualityRouteImport } from './routes/analytics.quality'
import { Route as AnalyticsRevenueRouteImport } from './routes/analytics.revenue'
import { Route as LguAnalyticsRouteImport } from './routes/lgu.analytics'
import { Route as LguReportsRouteImport } from './routes/lgu.reports'
import { Route as ReportsIndexRouteImport } from './routes/reports.index'
import { Route as ReportsReportIdRouteImport } from './routes/reports.$reportId'
import { Route as LguAnalyticsIndexRouteImport } from './routes/lgu.analytics.index'
import { Route as LguAnalyticsAlertsRouteImport } from './routes/lgu.analytics.alerts'
import { Route as LguAnalyticsCohortsRouteImport } from './routes/lgu.analytics.cohorts'
import { Route as LguAnalyticsExecutiveRouteImport } from './routes/lgu.analytics.executive'
import { Route as LguAnalyticsKonsultaRouteImport } from './routes/lgu.analytics.konsulta'
import { Route as LguAnalyticsMaternalRouteImport } from './routes/lgu.analytics.maternal'
import { Route as LguAnalyticsNcdRouteImport } from './routes/lgu.analytics.ncd'
import { Route as LguAnalyticsPatternsRouteImport } from './routes/lgu.analytics.patterns'
import { Route as LguAnalyticsPopulationRouteImport } from './routes/lgu.analytics.population'
import { Route as LguAnalyticsTbRouteImport } from './routes/lgu.analytics.tb'
import { Route as LguReportsIndexRouteImport } from './routes/lgu.reports.index'
import { Route as LguReportsReportIdRouteImport } from './routes/lgu.reports.$reportId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsIndexRoute = AnalyticsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AnalyticsRoute,
} as any)
const AnalyticsAlertsRoute = AnalyticsAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AnalyticsRoute,
} as any)
const AnalyticsClaimsRoute = AnalyticsClaimsRouteImport.update({
  id: '/claims',
  path: '/claims',
  getParentRoute: () => AnalyticsRoute,
} as any)
const AnalyticsClinicalRoute = AnalyticsClinicalRouteImport.update({
  id: '/clinical',
  path: '/clinical',
  getParentRoute: () => AnalyticsRoute,
} as any)
const AnalyticsCohortsRoute = AnalyticsCohortsRouteImport.update({
  id: '/cohorts',
  path: '/cohorts',
  getParentRoute: () => AnalyticsRoute,
} as any)
const AnalyticsExecutiveRoute = AnalyticsExecutiveRouteImport.update({
  id: '/executive',
  path: '/executive',
  getParentRoute: () => AnalyticsRoute,
} as any)
const AnalyticsLaboratoryRoute = AnalyticsLaboratoryRouteImport.update({
  id: '/laboratory',
  path: '/laboratory',
  getParentRoute: () => AnalyticsRoute,
} as any)
const AnalyticsNewChartsRoute = AnalyticsNewChartsRouteImport.update({
  id: '/new-charts',
  path: '/new-charts',
  getParentRoute: () => AnalyticsRoute,
} as any)
const AnalyticsPatientExperienceRoute =
  AnalyticsPatientExperienceRouteImport.update({
    id: '/patient-experience',
    path: '/patient-experience',
    getParentRoute: () => AnalyticsRoute,
  } as any)
const AnalyticsPatternsRoute = AnalyticsPatternsRouteImport.update({
  id: '/patterns',
  path: '/patterns',
  getParentRoute: () => AnalyticsRoute,
} as any)
const AnalyticsPerformanceRoute = AnalyticsPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => AnalyticsRoute,
} as any)
const AnalyticsQualityRoute = AnalyticsQualityRouteImport.update({
  id: '/quality',
  path: '/quality',
  getParentRoute: () => AnalyticsRoute,
} as any)
const AnalyticsRevenueRoute = AnalyticsRevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => AnalyticsRoute,
} as any)
const LguAnalyticsRoute = LguAnalyticsRouteImport.update({
  id: '/lgu/analytics',
  path: '/lgu/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const LguReportsRoute = LguReportsRouteImport.update({
  id: '/lgu/reports',
  path: '/lgu/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReportsRoute,
} as any)
const ReportsReportIdRoute = ReportsReportIdRouteImport.update({
  id: '/$reportId',
  path: '/$reportId',
  getParentRoute: () => ReportsRoute,
} as any)
const LguAnalyticsIndexRoute = LguAnalyticsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LguAnalyticsRoute,
} as any)
const LguAnalyticsAlertsRoute = LguAnalyticsAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => LguAnalyticsRoute,
} as any)
const LguAnalyticsCohortsRoute = LguAnalyticsCohortsRouteImport.update({
  id: '/cohorts',
  path: '/cohorts',
  getParentRoute: () => LguAnalyticsRoute,
} as any)
const LguAnalyticsExecutiveRoute = LguAnalyticsExecutiveRouteImport.update({
  id: '/executive',
  path: '/executive',
  getParentRoute: () => LguAnalyticsRoute,
} as any)
const LguAnalyticsKonsultaRoute = LguAnalyticsKonsultaRouteImport.update({
  id: '/konsulta',
  path: '/konsulta',
  getParentRoute: () => LguAnalyticsRoute,
} as any)
const LguAnalyticsMaternalRoute = LguAnalyticsMaternalRouteImport.update({
  id: '/maternal',
  path: '/maternal',
  getParentRoute: () => LguAnalyticsRoute,
} as any)
const LguAnalyticsNcdRoute = LguAnalyticsNcdRouteImport.update({
  id: '/ncd',
  path: '/ncd',
  getParentRoute: () => LguAnalyticsRoute,
} as any)
const LguAnalyticsPatternsRoute = LguAnalyticsPatternsRouteImport.update({
  id: '/patterns',
  path: '/patterns',
  getParentRoute: () => LguAnalyticsRoute,
} as any)
const LguAnalyticsPopulationRoute = LguAnalyticsPopulationRouteImport.update({
  id: '/population',
  path: '/population',
  getParentRoute: () => LguAnalyticsRoute,
} as any)
const LguAnalyticsTbRoute = LguAnalyticsTbRouteImport.update({
  id: '/tb',
  path: '/tb',
  getParentRoute: () => LguAnalyticsRoute,
} as any)
const LguReportsIndexRoute = LguReportsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LguReportsRoute,
} as any)
const LguReportsReportIdRoute = LguReportsReportIdRouteImport.update({
  id: '/$reportId',
  path: '/$reportId',
  getParentRoute: () => LguReportsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRouteWithChildren
  '/reports': typeof ReportsRouteWithChildren
  '/analytics/alerts': typeof AnalyticsAlertsRoute
  '/analytics/claims': typeof AnalyticsClaimsRoute
  '/analytics/clinical': typeof AnalyticsClinicalRoute
  '/analytics/cohorts': typeof AnalyticsCohortsRoute
  '/analytics/executive': typeof AnalyticsExecutiveRoute
  '/analytics/laboratory': typeof AnalyticsLaboratoryRoute
  '/analytics/new-charts': typeof AnalyticsNewChartsRoute
  '/analytics/patient-experience': typeof AnalyticsPatientExperienceRoute
  '/analytics/patterns': typeof AnalyticsPatternsRoute
  '/analytics/performance': typeof AnalyticsPerformanceRoute
  '/analytics/quality': typeof AnalyticsQualityRoute
  '/analytics/revenue': typeof AnalyticsRevenueRoute
  '/lgu/analytics': typeof LguAnalyticsRouteWithChildren
  '/lgu/reports': typeof LguReportsRouteWithChildren
  '/reports/$reportId': typeof ReportsReportIdRoute
  '/analytics/': typeof AnalyticsIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/lgu/analytics/alerts': typeof LguAnalyticsAlertsRoute
  '/lgu/analytics/cohorts': typeof LguAnalyticsCohortsRoute
  '/lgu/analytics/executive': typeof LguAnalyticsExecutiveRoute
  '/lgu/analytics/konsulta': typeof LguAnalyticsKonsultaRoute
  '/lgu/analytics/maternal': typeof LguAnalyticsMaternalRoute
  '/lgu/analytics/ncd': typeof LguAnalyticsNcdRoute
  '/lgu/analytics/patterns': typeof LguAnalyticsPatternsRoute
  '/lgu/analytics/population': typeof LguAnalyticsPopulationRoute
  '/lgu/analytics/tb': typeof LguAnalyticsTbRoute
  '/lgu/reports/$reportId': typeof LguReportsReportIdRoute
  '/lgu/analytics/': typeof LguAnalyticsIndexRoute
  '/lgu/reports/': typeof LguReportsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics/alerts': typeof AnalyticsAlertsRoute
  '/analytics/claims': typeof AnalyticsClaimsRoute
  '/analytics/clinical': typeof AnalyticsClinicalRoute
  '/analytics/cohorts': typeof AnalyticsCohortsRoute
  '/analytics/executive': typeof AnalyticsExecutiveRoute
  '/analytics/laboratory': typeof AnalyticsLaboratoryRoute
  '/analytics/new-charts': typeof AnalyticsNewChartsRoute
  '/analytics/patient-experience': typeof AnalyticsPatientExperienceRoute
  '/analytics/patterns': typeof AnalyticsPatternsRoute
  '/analytics/performance': typeof AnalyticsPerformanceRoute
  '/analytics/quality': typeof AnalyticsQualityRoute
  '/analytics/revenue': typeof AnalyticsRevenueRoute
  '/reports/$reportId': typeof ReportsReportIdRoute
  '/analytics': typeof AnalyticsIndexRoute
  '/reports': typeof ReportsIndexRoute
  '/lgu/analytics/alerts': typeof LguAnalyticsAlertsRoute
  '/lgu/analytics/cohorts': typeof LguAnalyticsCohortsRoute
  '/lgu/analytics/executive': typeof LguAnalyticsExecutiveRoute
  '/lgu/analytics/konsulta': typeof LguAnalyticsKonsultaRoute
  '/lgu/analytics/maternal': typeof LguAnalyticsMaternalRoute
  '/lgu/analytics/ncd': typeof LguAnalyticsNcdRoute
  '/lgu/analytics/patterns': typeof LguAnalyticsPatternsRoute
  '/lgu/analytics/population': typeof LguAnalyticsPopulationRoute
  '/lgu/analytics/tb': typeof LguAnalyticsTbRoute
  '/lgu/reports/$reportId': typeof LguReportsReportIdRoute
  '/lgu/analytics': typeof LguAnalyticsIndexRoute
  '/lgu/reports': typeof LguReportsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRouteWithChildren
  '/reports': typeof ReportsRouteWithChildren
  '/analytics/alerts': typeof AnalyticsAlertsRoute
  '/analytics/claims': typeof AnalyticsClaimsRoute
  '/analytics/clinical': typeof AnalyticsClinicalRoute
  '/analytics/cohorts': typeof AnalyticsCohortsRoute
  '/analytics/executive': typeof AnalyticsExecutiveRoute
  '/analytics/laboratory': typeof AnalyticsLaboratoryRoute
  '/analytics/new-charts': typeof AnalyticsNewChartsRoute
  '/analytics/patient-experience': typeof AnalyticsPatientExperienceRoute
  '/analytics/patterns': typeof AnalyticsPatternsRoute
  '/analytics/performance': typeof AnalyticsPerformanceRoute
  '/analytics/quality': typeof AnalyticsQualityRoute
  '/analytics/revenue': typeof AnalyticsRevenueRoute
  '/lgu/analytics': typeof LguAnalyticsRouteWithChildren
  '/lgu/reports': typeof LguReportsRouteWithChildren
  '/reports/$reportId': typeof ReportsReportIdRoute
  '/analytics/': typeof AnalyticsIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/lgu/analytics/alerts': typeof LguAnalyticsAlertsRoute
  '/lgu/analytics/cohorts': typeof LguAnalyticsCohortsRoute
  '/lgu/analytics/executive': typeof LguAnalyticsExecutiveRoute
  '/lgu/analytics/konsulta': typeof LguAnalyticsKonsultaRoute
  '/lgu/analytics/maternal': typeof LguAnalyticsMaternalRoute
  '/lgu/analytics/ncd': typeof LguAnalyticsNcdRoute
  '/lgu/analytics/patterns': typeof LguAnalyticsPatternsRoute
  '/lgu/analytics/population': typeof LguAnalyticsPopulationRoute
  '/lgu/analytics/tb': typeof LguAnalyticsTbRoute
  '/lgu/reports/$reportId': typeof LguReportsReportIdRoute
  '/lgu/analytics/': typeof LguAnalyticsIndexRoute
  '/lgu/reports/': typeof LguReportsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/reports'
    | '/analytics/alerts'
    | '/analytics/claims'
    | '/analytics/clinical'
    | '/analytics/cohorts'
    | '/analytics/executive'
    | '/analytics/laboratory'
    | '/analytics/new-charts'
    | '/analytics/patient-experience'
    | '/analytics/patterns'
    | '/analytics/performance'
    | '/analytics/quality'
    | '/analytics/revenue'
    | '/lgu/analytics'
    | '/lgu/reports'
    | '/reports/$reportId'
    | '/analytics/'
    | '/reports/'
    | '/lgu/analytics/alerts'
    | '/lgu/analytics/cohorts'
    | '/lgu/analytics/executive'
    | '/lgu/analytics/konsulta'
    | '/lgu/analytics/maternal'
    | '/lgu/analytics/ncd'
    | '/lgu/analytics/patterns'
    | '/lgu/analytics/population'
    | '/lgu/analytics/tb'
    | '/lgu/reports/$reportId'
    | '/lgu/analytics/'
    | '/lgu/reports/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics/alerts'
    | '/analytics/claims'
    | '/analytics/clinical'
    | '/analytics/cohorts'
    | '/analytics/executive'
    | '/analytics/laboratory'
    | '/analytics/new-charts'
    | '/analytics/patient-experience'
    | '/analytics/patterns'
    | '/analytics/performance'
    | '/analytics/quality'
    | '/analytics/revenue'
    | '/reports/$reportId'
    | '/analytics'
    | '/reports'
    | '/lgu/analytics/alerts'
    | '/lgu/analytics/cohorts'
    | '/lgu/analytics/executive'
    | '/lgu/analytics/konsulta'
    | '/lgu/analytics/maternal'
    | '/lgu/analytics/ncd'
    | '/lgu/analytics/patterns'
    | '/lgu/analytics/population'
    | '/lgu/analytics/tb'
    | '/lgu/reports/$reportId'
    | '/lgu/analytics'
    | '/lgu/reports'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/reports'
    | '/analytics/alerts'
    | '/analytics/claims'
    | '/analytics/clinical'
    | '/analytics/cohorts'
    | '/analytics/executive'
    | '/analytics/laboratory'
    | '/analytics/new-charts'
    | '/analytics/patient-experience'
    | '/analytics/patterns'
    | '/analytics/performance'
    | '/analytics/quality'
    | '/analytics/revenue'
    | '/lgu/analytics'
    | '/lgu/reports'
    | '/reports/$reportId'
    | '/analytics/'
    | '/reports/'
    | '/lgu/analytics/alerts'
    | '/lgu/analytics/cohorts'
    | '/lgu/analytics/executive'
    | '/lgu/analytics/konsulta'
    | '/lgu/analytics/maternal'
    | '/lgu/analytics/ncd'
    | '/lgu/analytics/patterns'
    | '/lgu/analytics/population'
    | '/lgu/analytics/tb'
    | '/lgu/reports/$reportId'
    | '/lgu/analytics/'
    | '/lgu/reports/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRouteWithChildren
  ReportsRoute: typeof ReportsRouteWithChildren
  LguAnalyticsRoute: typeof LguAnalyticsRouteWithChildren
  LguReportsRoute: typeof LguReportsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/': {
      id: '/analytics/'
      path: '/'
      fullPath: '/analytics/'
      preLoaderRoute: typeof AnalyticsIndexRouteImport
      parentRoute: typeof AnalyticsRoute
    }
    '/analytics/alerts': {
      id: '/analytics/alerts'
      path: '/alerts'
      fullPath: '/analytics/alerts'
      preLoaderRoute: typeof AnalyticsAlertsRouteImport
      parentRoute: typeof AnalyticsRoute
    }
    '/analytics/claims': {
      id: '/analytics/claims'
      path: '/claims'
      fullPath: '/analytics/claims'
      preLoaderRoute: typeof AnalyticsClaimsRouteImport
      parentRoute: typeof AnalyticsRoute
    }
    '/analytics/clinical': {
      id: '/analytics/clinical'
      path: '/clinical'
      fullPath: '/analytics/clinical'
      preLoaderRoute: typeof AnalyticsClinicalRouteImport
      parentRoute: typeof AnalyticsRoute
    }
    '/analytics/cohorts': {
      id: '/analytics/cohorts'
      path: '/cohorts'
      fullPath: '/analytics/cohorts'
      preLoaderRoute: typeof AnalyticsCohortsRouteImport
      parentRoute: typeof AnalyticsRoute
    }
    '/analytics/executive': {
      id: '/analytics/executive'
      path: '/executive'
      fullPath: '/analytics/executive'
      preLoaderRoute: typeof AnalyticsExecutiveRouteImport
      parentRoute: typeof AnalyticsRoute
    }
    '/analytics/laboratory': {
      id: '/analytics/laboratory'
      path: '/laboratory'
      fullPath: '/analytics/laboratory'
      preLoaderRoute: typeof AnalyticsLaboratoryRouteImport
      parentRoute: typeof AnalyticsRoute
    }
    '/analytics/new-charts': {
      id: '/analytics/new-charts'
      path: '/new-charts'
      fullPath: '/analytics/new-charts'
      preLoaderRoute: typeof AnalyticsNewChartsRouteImport
      parentRoute: typeof AnalyticsRoute
    }
    '/analytics/patient-experience': {
      id: '/analytics/patient-experience'
      path: '/patient-experience'
      fullPath: '/analytics/patient-experience'
      preLoaderRoute: typeof AnalyticsPatientExperienceRouteImport
      parentRoute: typeof AnalyticsRoute
    }
    '/analytics/patterns': {
      id: '/analytics/patterns'
      path: '/patterns'
      fullPath: '/analytics/patterns'
      preLoaderRoute: typeof AnalyticsPatternsRouteImport
      parentRoute: typeof AnalyticsRoute
    }
    '/analytics/performance': {
      id: '/analytics/performance'
      path: '/performance'
      fullPath: '/analytics/performance'
      preLoaderRoute: typeof AnalyticsPerformanceRouteImport
      parentRoute: typeof AnalyticsRoute
    }
    '/analytics/quality': {
      id: '/analytics/quality'
      path: '/quality'
      fullPath: '/analytics/quality'
      preLoaderRoute: typeof AnalyticsQualityRouteImport
      parentRoute: typeof AnalyticsRoute
    }
    '/analytics/revenue': {
      id: '/analytics/revenue'
      path: '/revenue'
      fullPath: '/analytics/revenue'
      preLoaderRoute: typeof AnalyticsRevenueRouteImport
      parentRoute: typeof AnalyticsRoute
    }
    '/lgu/analytics': {
      id: '/lgu/analytics'
      path: '/lgu/analytics'
      fullPath: '/lgu/analytics'
      preLoaderRoute: typeof LguAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lgu/reports': {
      id: '/lgu/reports'
      path: '/lgu/reports'
      fullPath: '/lgu/reports'
      preLoaderRoute: typeof LguReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/': {
      id: '/reports/'
      path: '/'
      fullPath: '/reports/'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/$reportId': {
      id: '/reports/$reportId'
      path: '/$reportId'
      fullPath: '/reports/$reportId'
      preLoaderRoute: typeof ReportsReportIdRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/lgu/analytics/': {
      id: '/lgu/analytics/'
      path: '/'
      fullPath: '/lgu/analytics/'
      preLoaderRoute: typeof LguAnalyticsIndexRouteImport
      parentRoute: typeof LguAnalyticsRoute
    }
    '/lgu/analytics/alerts': {
      id: '/lgu/analytics/alerts'
      path: '/alerts'
      fullPath: '/lgu/analytics/alerts'
      preLoaderRoute: typeof LguAnalyticsAlertsRouteImport
      parentRoute: typeof LguAnalyticsRoute
    }
    '/lgu/analytics/cohorts': {
      id: '/lgu/analytics/cohorts'
      path: '/cohorts'
      fullPath: '/lgu/analytics/cohorts'
      preLoaderRoute: typeof LguAnalyticsCohortsRouteImport
      parentRoute: typeof LguAnalyticsRoute
    }
    '/lgu/analytics/executive': {
      id: '/lgu/analytics/executive'
      path: '/executive'
      fullPath: '/lgu/analytics/executive'
      preLoaderRoute: typeof LguAnalyticsExecutiveRouteImport
      parentRoute: typeof LguAnalyticsRoute
    }
    '/lgu/analytics/konsulta': {
      id: '/lgu/analytics/konsulta'
      path: '/konsulta'
      fullPath: '/lgu/analytics/konsulta'
      preLoaderRoute: typeof LguAnalyticsKonsultaRouteImport
      parentRoute: typeof LguAnalyticsRoute
    }
    '/lgu/analytics/maternal': {
      id: '/lgu/analytics/maternal'
      path: '/maternal'
      fullPath: '/lgu/analytics/maternal'
      preLoaderRoute: typeof LguAnalyticsMaternalRouteImport
      parentRoute: typeof LguAnalyticsRoute
    }
    '/lgu/analytics/ncd': {
      id: '/lgu/analytics/ncd'
      path: '/ncd'
      fullPath: '/lgu/analytics/ncd'
      preLoaderRoute: typeof LguAnalyticsNcdRouteImport
      parentRoute: typeof LguAnalyticsRoute
    }
    '/lgu/analytics/patterns': {
      id: '/lgu/analytics/patterns'
      path: '/patterns'
      fullPath: '/lgu/analytics/patterns'
      preLoaderRoute: typeof LguAnalyticsPatternsRouteImport
      parentRoute: typeof LguAnalyticsRoute
    }
    '/lgu/analytics/population': {
      id: '/lgu/analytics/population'
      path: '/population'
      fullPath: '/lgu/analytics/population'
      preLoaderRoute: typeof LguAnalyticsPopulationRouteImport
      parentRoute: typeof LguAnalyticsRoute
    }
    '/lgu/analytics/tb': {
      id: '/lgu/analytics/tb'
      path: '/tb'
      fullPath: '/lgu/analytics/tb'
      preLoaderRoute: typeof LguAnalyticsTbRouteImport
      parentRoute: typeof LguAnalyticsRoute
    }
    '/lgu/reports/': {
      id: '/lgu/reports/'
      path: '/'
      fullPath: '/lgu/reports/'
      preLoaderRoute: typeof LguReportsIndexRouteImport
      parentRoute: typeof LguReportsRoute
    }
    '/lgu/reports/$reportId': {
      id: '/lgu/reports/$reportId'
      path: '/$reportId'
      fullPath: '/lgu/reports/$reportId'
      preLoaderRoute: typeof LguReportsReportIdRouteImport
      parentRoute: typeof LguReportsRoute
    }
  }
}

interface AnalyticsRouteChildren {
  AnalyticsAlertsRoute: typeof AnalyticsAlertsRoute
  AnalyticsClaimsRoute: typeof AnalyticsClaimsRoute
  AnalyticsClinicalRoute: typeof AnalyticsClinicalRoute
  AnalyticsCohortsRoute: typeof AnalyticsCohortsRoute
  AnalyticsExecutiveRoute: typeof AnalyticsExecutiveRoute
  AnalyticsLaboratoryRoute: typeof AnalyticsLaboratoryRoute
  AnalyticsNewChartsRoute: typeof AnalyticsNewChartsRoute
  AnalyticsPatientExperienceRoute: typeof AnalyticsPatientExperienceRoute
  AnalyticsPatternsRoute: typeof AnalyticsPatternsRoute
  AnalyticsPerformanceRoute: typeof AnalyticsPerformanceRoute
  AnalyticsQualityRoute: typeof AnalyticsQualityRoute
  AnalyticsRevenueRoute: typeof AnalyticsRevenueRoute
  AnalyticsIndexRoute: typeof AnalyticsIndexRoute
}

const AnalyticsRouteChildren: AnalyticsRouteChildren = {
  AnalyticsAlertsRoute: AnalyticsAlertsRoute,
  AnalyticsClaimsRoute: AnalyticsClaimsRoute,
  AnalyticsClinicalRoute: AnalyticsClinicalRoute,
  AnalyticsCohortsRoute: AnalyticsCohortsRoute,
  AnalyticsExecutiveRoute: AnalyticsExecutiveRoute,
  AnalyticsLaboratoryRoute: AnalyticsLaboratoryRoute,
  AnalyticsNewChartsRoute: AnalyticsNewChartsRoute,
  AnalyticsPatientExperienceRoute: AnalyticsPatientExperienceRoute,
  AnalyticsPatternsRoute: AnalyticsPatternsRoute,
  AnalyticsPerformanceRoute: AnalyticsPerformanceRoute,
  AnalyticsQualityRoute: AnalyticsQualityRoute,
  AnalyticsRevenueRoute: AnalyticsRevenueRoute,
  AnalyticsIndexRoute: AnalyticsIndexRoute,
}

const AnalyticsRouteWithChildren = AnalyticsRoute._addFileChildren(
  AnalyticsRouteChildren,
)

interface ReportsRouteChildren {
  ReportsReportIdRoute: typeof ReportsReportIdRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
}

const ReportsRouteChildren: ReportsRouteChildren = {
  ReportsReportIdRoute: ReportsReportIdRoute,
  ReportsIndexRoute: ReportsIndexRoute,
}

const ReportsRouteWithChildren =
  ReportsRoute._addFileChildren(ReportsRouteChildren)

interface LguAnalyticsRouteChildren {
  LguAnalyticsAlertsRoute: typeof LguAnalyticsAlertsRoute
  LguAnalyticsCohortsRoute: typeof LguAnalyticsCohortsRoute
  LguAnalyticsExecutiveRoute: typeof LguAnalyticsExecutiveRoute
  LguAnalyticsKonsultaRoute: typeof LguAnalyticsKonsultaRoute
  LguAnalyticsMaternalRoute: typeof LguAnalyticsMaternalRoute
  LguAnalyticsNcdRoute: typeof LguAnalyticsNcdRoute
  LguAnalyticsPatternsRoute: typeof LguAnalyticsPatternsRoute
  LguAnalyticsPopulationRoute: typeof LguAnalyticsPopulationRoute
  LguAnalyticsTbRoute: typeof LguAnalyticsTbRoute
  LguAnalyticsIndexRoute: typeof LguAnalyticsIndexRoute
}

const LguAnalyticsRouteChildren: LguAnalyticsRouteChildren = {
  LguAnalyticsAlertsRoute: LguAnalyticsAlertsRoute,
  LguAnalyticsCohortsRoute: LguAnalyticsCohortsRoute,
  LguAnalyticsExecutiveRoute: LguAnalyticsExecutiveRoute,
  LguAnalyticsKonsultaRoute: LguAnalyticsKonsultaRoute,
  LguAnalyticsMaternalRoute: LguAnalyticsMaternalRoute,
  LguAnalyticsNcdRoute: LguAnalyticsNcdRoute,
  LguAnalyticsPatternsRoute: LguAnalyticsPatternsRoute,
  LguAnalyticsPopulationRoute: LguAnalyticsPopulationRoute,
  LguAnalyticsTbRoute: LguAnalyticsTbRoute,
  LguAnalyticsIndexRoute: LguAnalyticsIndexRoute,
}

const LguAnalyticsRouteWithChildren = LguAnalyticsRoute._addFileChildren(
  LguAnalyticsRouteChildren,
)

interface LguReportsRouteChildren {
  LguReportsReportIdRoute: typeof LguReportsReportIdRoute
  LguReportsIndexRoute: typeof LguReportsIndexRoute
}

const LguReportsRouteChildren: LguReportsRouteChildren = {
  LguReportsReportIdRoute: LguReportsReportIdRoute,
  LguReportsIndexRoute: LguReportsIndexRoute,
}

const LguReportsRouteWithChildren = LguReportsRoute._addFileChildren(
  LguReportsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRouteWithChildren,
  ReportsRoute: ReportsRouteWithChildren,
  LguAnalyticsRoute: LguAnalyticsRouteWithChildren,
  LguReportsRoute: LguReportsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
